### ISSUE TITLE
Feature Request: Is there a way to "remove" a "loading" bubble, after the response has arrived?

### ISSUE THREAD

**Issue by mberkeland** [yishiashia/wc-chatbot#1]
It would be nice, for queries that take a few seconds, to show the "loading" bubble, but then remove/replace it with the response message once it arrives.

I am not seeing how to do this at first glance, so if it is not possible, it would certainly be a great enhancement!  But dang, I love this component... very simple and elegant.

**Comment by yishiashia** [comment]
Hi @mberkeland ,

Thank you for your feedback. You're right, the hide loading bubble feature is something I haven't implemented yet. I will make sure to add that functionality as soon as possible.

Please let me know if there's anything else I can assist with.

**Comment by yishiashia** [comment]
Hi @mberkeland ,

I'm pleased to let you know that a new release (v0.2.0) is now available. This release includes three new hiding functions, which are detailed in the updated README.md file.

Please feel free to review the changes and let me know if you have any other questions.

Best regards.

**Comment by mberkeland** [comment]
This works to remove the loading bubbles. Thank you for your quick response!!!  The only minor issue I see is that the "Loading" shows the avatar (good), but when you remove the loading and do the next sendMessage, the avatar is not there (bascially, a "continue" type bubble.  Setting continue: false does not help.

Again, this is a minor issue, but I thought I would point it out.  Thanks so much for the fantastic response!

**Comment by yishiashia** [comment]
Hi @mberkeland , 

I have tried on the demo page [https://yishiashia.github.io/wc-chatbot/](https://yishiashia.github.io/wc-chatbot/), but i cannot get a message bubble without avatar after hiding loading messages and do the next sendMessage. Would you please provide an example of how you call the functions that can repeat the situation? Thanks.

**Comment by mberkeland** [comment]
Thank you!
I was able to compare my code with yours, and I found the issue.
When sending the "loading: true" message to the chatbot, I was still
including the "sender" object in the options.  Once I removed that, it
behaved exactly as you said and showed.
Thanks again!!!  I truly appreciate the quick responses!
-Mark
